[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "asi"
version = "0.1.0"
description = "Prototype algorithms for self-improving AI"
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["asi"]
package-dir = {asi = "src"}
