# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: distributed_memory.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'distributed_memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64istributed_memory.proto\x12\x03\x61si\"+\n\x0bPushRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x0c\n\x04meta\x18\x02 \x01(\t\"\x17\n\tPushReply\x12\n\n\x02ok\x18\x01 \x01(\x08\")\n\x0cQueryRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\"8\n\nQueryReply\x12\x0f\n\x07vectors\x18\x01 \x03(\x02\x12\x0c\n\x04meta\x18\x02 \x03(\t\x12\x0b\n\x03\x64im\x18\x03 \x01(\x05\x32\x66\n\rMemoryService\x12(\n\x04Push\x12\x10.asi.PushRequest\x1a\x0e.asi.PushReply\x12+\n\x05Query\x12\x11.asi.QueryRequest\x1a\x0f.asi.QueryReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributed_memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHREQUEST']._serialized_start=33
  _globals['_PUSHREQUEST']._serialized_end=76
  _globals['_PUSHREPLY']._serialized_start=78
  _globals['_PUSHREPLY']._serialized_end=101
  _globals['_QUERYREQUEST']._serialized_start=103
  _globals['_QUERYREQUEST']._serialized_end=144
  _globals['_QUERYREPLY']._serialized_start=146
  _globals['_QUERYREPLY']._serialized_end=202
  _globals['_MEMORYSERVICE']._serialized_start=204
  _globals['_MEMORYSERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
