# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kg_memory.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'kg_memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkg_memory.proto\x12\x03\x61si\"`\n\x0bTripleEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x11\n\tpredicate\x18\x03 \x01(\t\x12\x0e\n\x06object\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\".\n\x0bTripleBatch\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.asi.TripleEntry\"\x17\n\tPushReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"A\n\x0bTripleQuery\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x11\n\tpredicate\x18\x02 \x01(\t\x12\x0e\n\x06object\x18\x03 \x01(\t2\xc1\x01\n\x0fKGMemoryService\x12(\n\x04Push\x12\x10.asi.TripleEntry\x1a\x0e.asi.PushReply\x12-\n\tPushBatch\x12\x10.asi.TripleBatch\x1a\x0e.asi.PushReply\x12+\n\x05Query\x12\x10.asi.TripleQuery\x1a\x10.asi.TripleBatch\x12(\n\x04Sync\x12\x10.asi.TripleBatch\x1a\x0e.asi.PushReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kg_memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIPLEENTRY']._serialized_start=24
  _globals['_TRIPLEENTRY']._serialized_end=120
  _globals['_TRIPLEBATCH']._serialized_start=122
  _globals['_TRIPLEBATCH']._serialized_end=168
  _globals['_PUSHREPLY']._serialized_start=170
  _globals['_PUSHREPLY']._serialized_end=193
  _globals['_TRIPLEQUERY']._serialized_start=195
  _globals['_TRIPLEQUERY']._serialized_end=260
  _globals['_KGMEMORYSERVICE']._serialized_start=263
  _globals['_KGMEMORYSERVICE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
