# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lineage.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'lineage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlineage.proto\x12\x03\x61si\"@\n\x0f\x41\x64\x64\x45ntryRequest\x12\x0c\n\x04note\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\"\x1b\n\rAddEntryReply\x12\n\n\x02ok\x18\x01 \x01(\x08\"?\n\x0bOutputEntry\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x14\n\x0cwatermark_id\x18\x03 \x01(\t\"H\n\x05\x45ntry\x12\x0c\n\x04note\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12!\n\x07outputs\x18\x03 \x03(\x0b\x32\x10.asi.OutputEntry\"\x13\n\x11GetEntriesRequest\".\n\x0fGetEntriesReply\x12\x1b\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\n.asi.Entry2\x89\x01\n\x15\x44\x61tasetLineageService\x12\x34\n\x08\x41\x64\x64\x45ntry\x12\x14.asi.AddEntryRequest\x1a\x12.asi.AddEntryReply\x12:\n\nGetEntries\x12\x16.asi.GetEntriesRequest\x1a\x14.asi.GetEntriesReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lineage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDENTRYREQUEST']._serialized_start=22
  _globals['_ADDENTRYREQUEST']._serialized_end=86
  _globals['_ADDENTRYREPLY']._serialized_start=88
  _globals['_ADDENTRYREPLY']._serialized_end=115
  _globals['_OUTPUTENTRY']._serialized_start=117
  _globals['_OUTPUTENTRY']._serialized_end=180
  _globals['_ENTRY']._serialized_start=182
  _globals['_ENTRY']._serialized_end=254
  _globals['_GETENTRIESREQUEST']._serialized_start=256
  _globals['_GETENTRIESREQUEST']._serialized_end=275
  _globals['_GETENTRIESREPLY']._serialized_start=277
  _globals['_GETENTRIESREPLY']._serialized_end=323
  _globals['_DATASETLINEAGESERVICE']._serialized_start=326
  _globals['_DATASETLINEAGESERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
