# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lineage_pb2 as lineage__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lineage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatasetLineageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddEntry = channel.unary_unary(
                '/asi.DatasetLineageService/AddEntry',
                request_serializer=lineage__pb2.AddEntryRequest.SerializeToString,
                response_deserializer=lineage__pb2.AddEntryReply.FromString,
                _registered_method=True)
        self.GetEntries = channel.unary_unary(
                '/asi.DatasetLineageService/GetEntries',
                request_serializer=lineage__pb2.GetEntriesRequest.SerializeToString,
                response_deserializer=lineage__pb2.GetEntriesReply.FromString,
                _registered_method=True)


class DatasetLineageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatasetLineageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEntry,
                    request_deserializer=lineage__pb2.AddEntryRequest.FromString,
                    response_serializer=lineage__pb2.AddEntryReply.SerializeToString,
            ),
            'GetEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntries,
                    request_deserializer=lineage__pb2.GetEntriesRequest.FromString,
                    response_serializer=lineage__pb2.GetEntriesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asi.DatasetLineageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asi.DatasetLineageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatasetLineageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asi.DatasetLineageService/AddEntry',
            lineage__pb2.AddEntryRequest.SerializeToString,
            lineage__pb2.AddEntryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asi.DatasetLineageService/GetEntries',
            lineage__pb2.GetEntriesRequest.SerializeToString,
            lineage__pb2.GetEntriesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
