# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"8\n\nAddRequest\x12\x18\n\x07vectors\x18\x01 \x03(\x0b\x32\x07.Vector\x12\x10\n\x08metadata\x18\x02 \x03(\t\"\x07\n\x05\x45mpty\"1\n\x0cQueryRequest\x12\x16\n\x05query\x18\x01 \x01(\x0b\x32\x07.Vector\x12\t\n\x01k\x18\x02 \x01(\x05\"9\n\x0bQueryResult\x12\x18\n\x07vectors\x18\x01 \x03(\x0b\x32\x07.Vector\x12\x10\n\x08metadata\x18\x02 \x03(\t2Q\n\rMemoryService\x12\x1a\n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x06.Empty\x12$\n\x05Query\x12\r.QueryRequest\x1a\x0c.QueryResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR']._serialized_start=16
  _globals['_VECTOR']._serialized_end=40
  _globals['_ADDREQUEST']._serialized_start=42
  _globals['_ADDREQUEST']._serialized_end=98
  _globals['_EMPTY']._serialized_start=100
  _globals['_EMPTY']._serialized_end=107
  _globals['_QUERYREQUEST']._serialized_start=109
  _globals['_QUERYREQUEST']._serialized_end=158
  _globals['_QUERYRESULT']._serialized_start=160
  _globals['_QUERYRESULT']._serialized_end=217
  _globals['_MEMORYSERVICE']._serialized_start=219
  _globals['_MEMORYSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
