# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x12\x03\x61si\"/\n\x0bPushRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x10\n\x08metadata\x18\x02 \x01(\t\"\x17\n\tPushReply\x12\n\n\x02ok\x18\x01 \x01(\x08\")\n\x0cQueryRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\"/\n\nQueryReply\x12\x0f\n\x07vectors\x18\x01 \x03(\x02\x12\x10\n\x08metadata\x18\x02 \x03(\t2f\n\rMemoryService\x12(\n\x04Push\x12\x10.asi.PushRequest\x1a\x0e.asi.PushReply\x12+\n\x05Query\x12\x11.asi.QueryRequest\x1a\x0f.asi.QueryReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHREQUEST']._serialized_start=21
  _globals['_PUSHREQUEST']._serialized_end=68
  _globals['_PUSHREPLY']._serialized_start=70
  _globals['_PUSHREPLY']._serialized_end=93
  _globals['_QUERYREQUEST']._serialized_start=95
  _globals['_QUERYREQUEST']._serialized_end=136
  _globals['_QUERYREPLY']._serialized_start=138
  _globals['_QUERYREPLY']._serialized_end=185
  _globals['_MEMORYSERVICE']._serialized_start=187
  _globals['_MEMORYSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
