# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reasoning_graph_pb2 as reasoning__graph__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reasoning_graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReasoningGraphServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Push = channel.unary_unary(
                '/asi.ReasoningGraphService/Push',
                request_serializer=reasoning__graph__pb2.NodeEntry.SerializeToString,
                response_deserializer=reasoning__graph__pb2.PushReply.FromString,
                _registered_method=True)
        self.PushBatch = channel.unary_unary(
                '/asi.ReasoningGraphService/PushBatch',
                request_serializer=reasoning__graph__pb2.NodeBatch.SerializeToString,
                response_deserializer=reasoning__graph__pb2.PushReply.FromString,
                _registered_method=True)
        self.Sync = channel.unary_unary(
                '/asi.ReasoningGraphService/Sync',
                request_serializer=reasoning__graph__pb2.NodeBatch.SerializeToString,
                response_deserializer=reasoning__graph__pb2.PushReply.FromString,
                _registered_method=True)


class ReasoningGraphServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Push(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReasoningGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=reasoning__graph__pb2.NodeEntry.FromString,
                    response_serializer=reasoning__graph__pb2.PushReply.SerializeToString,
            ),
            'PushBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PushBatch,
                    request_deserializer=reasoning__graph__pb2.NodeBatch.FromString,
                    response_serializer=reasoning__graph__pb2.PushReply.SerializeToString,
            ),
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=reasoning__graph__pb2.NodeBatch.FromString,
                    response_serializer=reasoning__graph__pb2.PushReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asi.ReasoningGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asi.ReasoningGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReasoningGraphService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asi.ReasoningGraphService/Push',
            reasoning__graph__pb2.NodeEntry.SerializeToString,
            reasoning__graph__pb2.PushReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asi.ReasoningGraphService/PushBatch',
            reasoning__graph__pb2.NodeBatch.SerializeToString,
            reasoning__graph__pb2.PushReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asi.ReasoningGraphService/Sync',
            reasoning__graph__pb2.NodeBatch.SerializeToString,
            reasoning__graph__pb2.PushReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
